// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_Casa_Criancas.Models;

#nullable disable

namespace Projeto_Casa_Criancas.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241122170309_AAAAAAAA")]
    partial class AAAAAAAA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("data")
                        .HasColumnType("date");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("responsavelID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("responsavelID");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.AssistenteSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("AssistentesSociais");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Chamada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("data")
                        .HasColumnType("date");

                    b.Property<int>("matriculaID")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("matriculaID");

                    b.ToTable("Chamadas");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Consultas.MatriculaAnoMes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ano")
                        .HasColumnType("int");

                    b.Property<int>("mes")
                        .HasColumnType("int");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("MatriculaAnoMes");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Consultas.MatriculaGrp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aluno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdeAluno")
                        .HasColumnType("int");

                    b.Property<int>("turma")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("MatriculaGrp");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Consultas.PivotMatricula", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("abril")
                        .HasColumnType("real");

                    b.Property<float>("agosto")
                        .HasColumnType("real");

                    b.Property<string>("ano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("dezembro")
                        .HasColumnType("real");

                    b.Property<float>("fevereiro")
                        .HasColumnType("real");

                    b.Property<float>("janeiro")
                        .HasColumnType("real");

                    b.Property<float>("julho")
                        .HasColumnType("real");

                    b.Property<float>("junho")
                        .HasColumnType("real");

                    b.Property<float>("maio")
                        .HasColumnType("real");

                    b.Property<float>("marco")
                        .HasColumnType("real");

                    b.Property<float>("novembro")
                        .HasColumnType("real");

                    b.Property<float>("outubro")
                        .HasColumnType("real");

                    b.Property<float>("setembro")
                        .HasColumnType("real");

                    b.Property<float>("total")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("PivotMatricula");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Consultas.TurmaGrp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("colaborador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("curso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TurmaGrp");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("colaboradorID")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.HasIndex("colaboradorID");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.HorarioDasAulas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviacao")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DiaDaSemana")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HoraFim")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HoraInicio")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("HorarioDasAulas");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("alunoID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("data")
                        .HasColumnType("date");

                    b.Property<int>("turmaID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("alunoID");

                    b.HasIndex("turmaID");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("Monitores");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("cursoId")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("horarioDasAulasID")
                        .HasColumnType("int");

                    b.Property<int>("monitorId")
                        .HasColumnType("int");

                    b.Property<int>("professorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cursoId");

                    b.HasIndex("horarioDasAulasID");

                    b.HasIndex("monitorId");

                    b.HasIndex("professorId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Visita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("acoesPreliminares")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("alunoID")
                        .HasColumnType("int");

                    b.Property<int>("assistenteSocialID")
                        .HasColumnType("int");

                    b.Property<string>("compactacoes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("contextoExterno")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("contextoFamiliar")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("data")
                        .HasColumnType("date");

                    b.Property<string>("encaminhamento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("escolarizacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("redeApoio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("situacaoFamiliar")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("violacaoDireito")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("violenciaDomestica")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("alunoID");

                    b.HasIndex("assistenteSocialID");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Aluno", b =>
                {
                    b.HasOne("Projeto_Casa_Criancas.Models.Responsavel", "responsavel")
                        .WithMany()
                        .HasForeignKey("responsavelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("responsavel");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Chamada", b =>
                {
                    b.HasOne("Projeto_Casa_Criancas.Models.Matricula", "matricula")
                        .WithMany()
                        .HasForeignKey("matriculaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("matricula");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Curso", b =>
                {
                    b.HasOne("Projeto_Casa_Criancas.Models.Colaborador", "colaborador")
                        .WithMany()
                        .HasForeignKey("colaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("colaborador");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Matricula", b =>
                {
                    b.HasOne("Projeto_Casa_Criancas.Models.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_Casa_Criancas.Models.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Turma", b =>
                {
                    b.HasOne("Projeto_Casa_Criancas.Models.Curso", "curso")
                        .WithMany()
                        .HasForeignKey("cursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_Casa_Criancas.Models.HorarioDasAulas", "horarioDasAulas")
                        .WithMany()
                        .HasForeignKey("horarioDasAulasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_Casa_Criancas.Models.Monitor", "monitor")
                        .WithMany()
                        .HasForeignKey("monitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_Casa_Criancas.Models.Professor", "professor")
                        .WithMany()
                        .HasForeignKey("professorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("curso");

                    b.Navigation("horarioDasAulas");

                    b.Navigation("monitor");

                    b.Navigation("professor");
                });

            modelBuilder.Entity("Projeto_Casa_Criancas.Models.Visita", b =>
                {
                    b.HasOne("Projeto_Casa_Criancas.Models.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto_Casa_Criancas.Models.AssistenteSocial", "assistenteSocial")
                        .WithMany()
                        .HasForeignKey("assistenteSocialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("assistenteSocial");
                });
#pragma warning restore 612, 618
        }
    }
}
